### ISSUE TITLE
Questions regarding data

### ISSUE THREAD

**Issue by gentrexha** [rexshijaku/alb-fake-news-corpus#1]
Greetings,

Excellent job! I absolutely enjoy what you've done here. 💯 👍 

I'd want to learn more about your methodology for producing and defining this data. I'd appreciate it if you could provide some light on some of my concerns:

1. How did you collect this data?
2. Where did you get your data?
3. What was your approach or criterion for identifying fake articles?
4. What method did you apply for POS labeling of individual tokens?
5. Do you mind if I upload a processed dataframe version of this dataset to Kaggle for public viewing? As intended, I would credit you as the original source.

Best regards,
Gent

**Comment by rexshijaku** [comment]
Hi/Tung @gentrexha 

First of all, we thank you for your good words!

All of your questions have their answers in our about-to-be-published work. I got your email (from your Github profile) and by now you should've received the PDF of the manuscript of our work. Check it out! 

Lastly, regarding your question (5). You definitely can do that, just when you mention please cite the name of our work as 'Albanian fake news detection' and the name of the journal in which it will be published as 'The ACM Transactions on Asian and Low-Resource Language Information Processing (TALLIP)' alongside authors. 

We wish you build up something powerful on that!
